name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set working dir
      run: cd ./src/extension/edunext-automation
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      
    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        
    - name: install deps
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Build
      run: npm build
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: extension-unpacked
        path: ./dist/
        warn: Cannot retrive extension!
        if-no-files-found: warn
        retention-days: 30
